# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-11-16 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20221116_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
